In [1]:
# Python libs
import pandas as pd

# Magics
from helpers import (
    load_sql_magic,
)
load_sql_magic()          # %%sql   — query DataFrames via duckdb (no extra installs)

True

In [2]:
import duckdb

DB_PATH = "./data/ab_events.duckdb"

con = duckdb.connect(DB_PATH, read_only=True)
event_log = con.execute("SELECT * FROM events").df()
con.close()

print(event_log.shape)
event_log.head()

(2024484, 7)

,date,user_id,hash_id,country,experiment,event_type,amount
0,2025-01-01 21:01:12,5,7674613650421074157,US,"{""num01"":""a""}",page_view,NaN
1,2025-01-01 21:02:09,5,7674613650421074157,US,"{""num01"":""a""}",page_view,NaN
2,2025-01-01 14:45:14,6,1310192797669293303,GB,"{""num01"":""a""}",page_view,NaN
3,2025-01-01 14:46:03,6,1310192797669293303,GB,"{""num01"":""a""}",page_view,NaN
4,2025-01-01 22:36:08,7,1750302349509622455,US,"{""num01"":""a""}",page_view,NaN

In [3]:
with duckdb.connect(DB_PATH, read_only=True) as con:
    df = con.execute("SHOW tables").df()

print(df)

                     name
0                  events
1    fct_ab_buckets_daily
2  int_ab_events_bucketed
3           stg_event_log

In [4]:
%%sql

SELECT * FROM event_log

,date,user_id,hash_id,country,experiment,event_type,amount
0,2025-01-01 21:01:12,5,7674613650421074157,US,"{""num01"":""a""}",page_view,NaN
1,2025-01-01 21:02:09,5,7674613650421074157,US,"{""num01"":""a""}",page_view,NaN
2,2025-01-01 14:45:14,6,1310192797669293303,GB,"{""num01"":""a""}",page_view,NaN
3,2025-01-01 14:46:03,6,1310192797669293303,GB,"{""num01"":""a""}",page_view,NaN
4,2025-01-01 22:36:08,7,1750302349509622455,US,"{""num01"":""a""}",page_view,NaN
...,...,...,...,...,...,...,...
2024479,2025-02-28 23:19:03,25000,4860591953457782041,GB,"{""num01"":""a""}",page_view,NaN
2024480,2025-02-28 23:19:44,25000,4860591953457782041,GB,"{""num01"":""a""}",page_view,NaN
2024481,2025-02-28 23:20:04,25000,4860591953457782041,GB,"{""num01"":""a""}",page_view,NaN
2024482,2025-02-28 23:21:08,25000,4860591953457782041,GB,"{""num01"":""a""}",page_view,NaN
2024483,2025-02-28 23:24:40,25000,4860591953457782041,GB,"{""num01"":""a""}",watch,NaN

In [8]:
with duckdb.connect(DB_PATH, read_only=True) as con:
    fct_ab_buckets_daily = con.execute("SELECT * FROM fct_ab_buckets_daily").df()

In [10]:
%%sql buckets <<

SELECT * FROM fct_ab_buckets_daily

,date_day,country,bucket,experiment_number,experiment_group,total_events,page_view_count,watch_count,add_to_cart_count,purchase_count,total_unique_users,u_page_view,u_watch,u_add_to_cart,u_purchase,purchase_amount
0,2025-01-10,US,172,num01,a,18,15,2,1,0,4,4,2,1,0,0.00
1,2025-01-10,DE,33,num01,b,4,3,1,0,0,1,1,1,0,0,0.00
2,2025-01-10,US,155,num01,b,19,15,2,1,1,4,4,2,1,1,44.15
3,2025-01-10,DE,185,num01,a,27,21,4,2,0,6,6,4,2,0,0.00
4,2025-01-10,US,97,num01,b,28,26,2,0,0,4,4,2,0,0,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
69197,2025-02-25,GB,148,num01,b,11,10,1,0,0,2,2,1,0,0,0.00
69198,2025-02-25,GB,102,num01,a,3,3,0,0,0,1,1,0,0,0,0.00
69199,2025-02-25,DE,105,num01,a,11,7,2,1,1,2,2,2,1,1,24.91
69200,2025-02-25,GB,159,num01,a,4,3,1,0,0,1,1,1,0,0,0.00
69201,2025-02-25,GB,65,num01,b,18,14,2,1,1,1,1,1,1,1,31.54

In [13]:
buckets[
    (buckets.date_day=="2025-01-10")
    & (buckets.country=='US')
]

,date_day,country,bucket,experiment_number,experiment_group,total_events,page_view_count,watch_count,add_to_cart_count,purchase_count,total_unique_users,u_page_view,u_watch,u_add_to_cart,u_purchase,purchase_amount
0,2025-01-10,US,172,num01,a,18,15,2,1,0,4,4,2,1,0,0.00
2,2025-01-10,US,155,num01,b,19,15,2,1,1,4,4,2,1,1,44.15
4,2025-01-10,US,97,num01,b,28,26,2,0,0,4,4,2,0,0,0.00
5,2025-01-10,US,9,num01,a,52,42,8,1,1,12,12,8,1,1,100.17
6,2025-01-10,US,86,num01,a,57,52,5,0,0,13,13,5,0,0,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
60685,2025-01-10,US,193,num01,a,31,26,5,0,0,5,5,4,0,0,0.00
60692,2025-01-10,US,129,num01,a,6,6,0,0,0,3,3,0,0,0,0.00
60694,2025-01-10,US,63,num01,b,10,8,2,0,0,3,3,2,0,0,0.00
60701,2025-01-10,US,94,num01,b,21,19,2,0,0,5,5,2,0,0,0.00
68441,2025-01-10,US,171,num01,a,17,14,3,0,0,6,6,3,0,0,0.00